name: ApiDOM Validator
description: This GitHub Action validates OpenAPI 3.x.y / AsyncAPI 2.x definition file using ApiDOM Language Service.
inputs:
  definition-file:
    description: Path to definition file
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.definition-file }}
branding:
  icon: 'file-text'
  color: 'green'
